import "~/styles/globals.css";

import clsx from "clsx";
import localFont from "next/font/local";

const outfit = localFont({
  src: [
    {
      path: "../../public/fonts/outfit/Outfit-VariableFont_wght.ttf",
    },
  ],
  variable: "--font-outfit",
});

const youngSerif = localFont({
  src: "../../public/fonts/young-serif/YoungSerif-Regular.ttf",
  variable: "--font-young-serif",
});

export const metadata = {
  title: "Recipe Page | FrontendMentor",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(
        outfit.variable,
        youngSerif.variable,
        "m-auto min-h-[100svh] w-[375px] min-w-[375px] max-w-3xl bg-secondary-eggshell p-4 font-outfit sm:w-full",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
